#pragma once


// activate keys to accept input from
#define KEYBOARD_A 1
#define KEYBOARD_B 0
#define KEYBOARD_C 0
#define KEYBOARD_D 1
#define KEYBOARD_E 0
#define KEYBOARD_F 0
#define KEYBOARD_G 0
#define KEYBOARD_H 0
#define KEYBOARD_I 0
#define KEYBOARD_J 0
#define KEYBOARD_K 0
#define KEYBOARD_L 0
#define KEYBOARD_M 0
#define KEYBOARD_N 0
#define KEYBOARD_O 0
#define KEYBOARD_P 0
#define KEYBOARD_Q 0
#define KEYBOARD_R 0
#define KEYBOARD_S 1
#define KEYBOARD_T 0
#define KEYBOARD_U 0
#define KEYBOARD_V 0
#define KEYBOARD_W 1
#define KEYBOARD_X 0
#define KEYBOARD_Y 0
#define KEYBOARD_Z 0
#define KEYBOARD_0 0
#define KEYBOARD_1 1
#define KEYBOARD_2 1
#define KEYBOARD_3 1
#define KEYBOARD_4 1
#define KEYBOARD_5 0
#define KEYBOARD_6 0
#define KEYBOARD_7 0
#define KEYBOARD_8 0
#define KEYBOARD_9 0
#define KEYBOARD_UP 0
#define KEYBOARD_DOWN 0
#define KEYBOARD_LEFT 0
#define KEYBOARD_RIGHT 0
#define KEYBOARD_RETURN 0
#define KEYBOARD_ESCAPE 0
#define KEYBOARD_SPACE 1
#define KEYBOARD_PLUS 0
#define KEYBOARD_MINUS 0
#define KEYBOARD_MULTIPLY 0
#define KEYBOARD_DIVIDE 0


namespace input
{
	constexpr size_t N_KEYBOARD_KEYS = 
	KEYBOARD_A + 
	KEYBOARD_B + 
	KEYBOARD_C + 
	KEYBOARD_D + 
	KEYBOARD_E + 
	KEYBOARD_F + 
	KEYBOARD_G + 
	KEYBOARD_H + 
	KEYBOARD_I + 
	KEYBOARD_J + 
	KEYBOARD_K + 
	KEYBOARD_L + 
	KEYBOARD_M + 
	KEYBOARD_N + 
	KEYBOARD_O + 
	KEYBOARD_P + 
	KEYBOARD_Q + 
	KEYBOARD_R + 
	KEYBOARD_S + 
	KEYBOARD_T + 
	KEYBOARD_U + 
	KEYBOARD_V + 
	KEYBOARD_W + 
	KEYBOARD_X + 
	KEYBOARD_Y + 
	KEYBOARD_Z + 
	KEYBOARD_0 + 
	KEYBOARD_1 + 
	KEYBOARD_2 + 
	KEYBOARD_3 + 
	KEYBOARD_4 + 
	KEYBOARD_5 + 
	KEYBOARD_6 + 
	KEYBOARD_7 + 
	KEYBOARD_8 + 
	KEYBOARD_9 + 
	KEYBOARD_UP + 
	KEYBOARD_DOWN + 
	KEYBOARD_LEFT + 
	KEYBOARD_RIGHT + 
	KEYBOARD_RETURN + 
	KEYBOARD_ESCAPE + 
	KEYBOARD_SPACE + 
	KEYBOARD_PLUS + 
	KEYBOARD_MINUS + 
	KEYBOARD_MULTIPLY + 
	KEYBOARD_DIVIDE;
}
